### ISSUE TITLE
How to listen to Jitsi's OPEN_CHAT and CLOSE_CHAT actions

### ISSUE THREAD

**Issue by hypnocill** [vidit-me/react-native-jitsi-meet#5]
@TacticCoder I see that you have exposed node_modules/@vidit-me/react-native-jitsi-meet/src/types.ts -> BroadcastActions but is it possible to somehow listen fo those actions when dispatched from Jitsi?

I'm using a custom Jitsi SDK build and as far as I see, those are dispatched from their JS, then get in native so there should be a way to finally get to listen to those events in my app's JS? I need to hook up to the chat opening event.

I'd appreciate any help, thank you!

**Comment by TacticCoder** [comment]
@hypnocill Hi, can you please attach some snippets ?

**Comment by hypnocill** [comment]
@TacticCoder I don't really have any since I'm currently just looking for ways to implement that but I was looking at these files in jitsi-meet:
https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/java/org/jitsi/meet/sdk/ExternalAPIModule.java
https://github.com/jitsi/jitsi-meet/blob/47bdf800e75e204bcea73a220e1dffa9afc73240/ios/sdk/src/ExternalAPI.m
https://github.com/jitsi/jitsi-meet/blob/44a9363f5b0803b47b13e3920b8481e03ac35a8d/react/features/mobile/external-api/middleware.js

I'm interested in getting to listen for the 'OPEN_CHAT' event in my app (which uses custom jitsk build for the JitsiMeetSDK both iOS and Android, currently very minor modifications and @vidit-me/react-native-jitsi-meet for the RN wrapper).

**Comment by hypnocill** [comment]
@TacticCoder - I managed to get it working on Android even though now I get a crash when I try to close the jitsi creen - 'FragmentManager is already executing transactions'.

For iOS though, I just can't seem to get it working. For instance, I followed the exposed 'onConferenceWillJoin' event carefully and in the same way I added my new custom event in the custom jitsi SDK and in the vidit-me/react-native-jitsi-meet's native part. Yet it doesn't work...

**Comment by TacticCoder** [comment]
@hypnocill can you provide some snippets of your work please?

**Comment by hypnocill** [comment]
@TacticCoder I asked for that in the jitsi community forum too and it seems that it's supposed to work the way I did it so it's probably some mistake I've done in objective c code (which I'm not familiar at all). I'll try to look into it further myself to not bother you.

Thank you, I'm closing the issue now
